create or replace view public.vw_triangle_opportunities_enriched as
SELECT
    id,
    run_id,
    run_time,
    run_parameters,
    "timestamp",
    trade_date,
    path,
    triangle_key,
    curr_a,
    curr_b,
    curr_c,
    profit_raw_pct / 100.0 AS profit_raw_pct,
    profit_net_pct / 100.0 AS profit_net_pct,
    rate_ab,
    rate_bc,
    rate_ca,
    pair_ab,
    pair_bc,
    pair_ca,
    dir_ab,
    dir_bc,
    dir_ca,
    min_volume,
    volume_usd_ab,
    volume_usd_bc,
    volume_usd_ca,
    min_quote_volume,
    min_trades,
    created_at,
    hour_time,
    rv24_ab,
    range24_ab,
    liq24_ab,
    cov24_ab,
    rv24_bc,
    range24_bc,
    liq24_bc,
    cov24_bc,
    rv24_ca,
    range24_ca,
    liq24_ca,
    cov24_ca,
    rv168_ab,
    rv168_bc,
    rv168_ca,
    rv720_ab,
    rv720_bc,
    rv720_ca,
    volcv_ab,
    volcv_bc,
    volcv_ca,
    tri_rv24h_max,
    tri_rv24h_mean,
    tri_rv168h_max,
    tri_rv720h_max,
    tri_range24h_max,
    tri_liq24h_min,
    tri_cov24h_min,
    tri_volcv24h_max
FROM public.triangle_opportunities_enriched;




